"""
Gold code generator module.

Gold codes are constructed from preferred pairs of m-sequences and are useful when we want
longer sync words or multiple distinguishable preambles with bounded
cross-correlation.

Supported Gold-code lengths are the sequence lengths generated by the preferred
pairs below in this LFSR convention.
"""

from __future__ import annotations

import numpy as np


# Preferred-pair taps for the Fibonacci LFSR convention used in this project.
# Each tap tuple lists positions counted from the output end: state[-tap].
_PREFERRED_GOLD_PAIRS = {
    3: ((1, 2), (1, 3)),
    5: ((1, 3), (1, 2, 3, 4)),
    6: ((1, 2), (1, 2, 3, 6)),
    7: ((1, 2), (1, 4)),
}

SUPPORTED_GOLD_LENGTHS = tuple(sorted((2**order) - 1 for order in _PREFERRED_GOLD_PAIRS))


def _generate_m_sequence_bits(order: int, taps: tuple[int, ...]) -> np.ndarray:
    length = (2**order) - 1
    state = np.ones(order, dtype=np.uint8)
    sequence = np.empty(length, dtype=np.uint8)

    for index in range(length):
        sequence[index] = state[-1]
        feedback = 0
        for tap in taps:
            feedback ^= int(state[-tap])
        state[1:] = state[:-1]
        state[0] = feedback

    return sequence


def _bits_to_bpsk(bits: np.ndarray) -> np.ndarray:
    return (1 - 2 * bits.astype(np.int8)).astype(np.int8)


def _length_to_order(code_length: int) -> int:
    for order in _PREFERRED_GOLD_PAIRS:
        if (2**order) - 1 == code_length:
            return order
    raise ValueError(
        f"Unsupported Gold code length: {code_length}. "
        f"Supported lengths are {SUPPORTED_GOLD_LENGTHS}."
    )


def build_gold_family_bits(code_length: int) -> tuple[np.ndarray, ...]:
    """
    Build one full Gold-code family for the requested code length.

    The returned family contains:
        index 0: first m-sequence
        index 1: second m-sequence
        index 2 + k: XOR of first m-sequence with the second sequence shifted by k
    """
    order = _length_to_order(code_length)
    taps_a, taps_b = _PREFERRED_GOLD_PAIRS[order]
    seq_a = _generate_m_sequence_bits(order, taps_a)
    seq_b = _generate_m_sequence_bits(order, taps_b)

    family: list[np.ndarray] = [seq_a.copy(), seq_b.copy()]
    for shift in range(code_length):
        family.append(np.bitwise_xor(seq_a, np.roll(seq_b, shift)))
    return tuple(family)


GOLD_CODE_FAMILIES_BITS = {
    code_length: build_gold_family_bits(code_length)
    for code_length in SUPPORTED_GOLD_LENGTHS
}

GOLD_CODE_FAMILIES_SYMBOLS = {
    "BPSK": {
        code_length: tuple(_bits_to_bpsk(bits) for bits in family)
        for code_length, family in GOLD_CODE_FAMILIES_BITS.items()
    },
    "QPSK": {
        code_length: tuple(
            (
                _bits_to_bpsk(bits).astype(np.float32)
                + 1j * _bits_to_bpsk(bits).astype(np.float32)
            ).astype(np.complex64)
            for bits in family
        )
        for code_length, family in GOLD_CODE_FAMILIES_BITS.items()
    },
}


def normalize_code_index(code_length: int, code_index: int) -> int:
    family_size = len(GOLD_CODE_FAMILIES_BITS[code_length])
    return int(code_index) % family_size


def get_gold_code_bits(code_length: int, code_index: int = 0) -> np.ndarray:
    normalized_index = normalize_code_index(code_length, code_index)
    return GOLD_CODE_FAMILIES_BITS[code_length][normalized_index].copy()


def get_gold_code_symbols(
    modulation_type: str,
    code_length: int,
    code_index: int = 0,
) -> np.ndarray:
    modulation_type = modulation_type.upper().strip()
    normalized_index = normalize_code_index(code_length, code_index)
    try:
        return GOLD_CODE_FAMILIES_SYMBOLS[modulation_type][code_length][normalized_index].copy()
    except KeyError as exc:
        raise ValueError(
            f"Unsupported Gold code configuration: modulation_type={modulation_type}, "
            f"code_length={code_length}"
        ) from exc


if __name__ == "__main__":
    print(f"Supported Gold lengths: {SUPPORTED_GOLD_LENGTHS}")
    for modulation in ("BPSK", "QPSK"):
        print(f"{modulation}:")
        for code_length in SUPPORTED_GOLD_LENGTHS:
            family_size = len(GOLD_CODE_FAMILIES_BITS[code_length])
            first = get_gold_code_symbols(modulation, code_length, code_index=0)
            third = get_gold_code_symbols(modulation, code_length, code_index=2)
            print(
                f"  length={code_length}, family_size={family_size}, "
                f"idx0={first[:8]}, idx2={third[:8]}"
            )
