radio:
  center_frequency: 866.5e6           # 866.5 MHz
  sample_rate: 2e6                    # 2 MS/s
  bandwidth: 7e6                      # 7 MHz [863 - 870 MHz]

transmitter:
  tx_enable: false                    # Enable/disable transmitter
  tx_cyclic_buffer_enable: false      # Enable/disable cyclic buffer
  tx_gain_dB: -50                     # range: -90 to 0 dB

receiver: 
  rx_enable: true                     # Enable/disable receiver
  rx_gain_dB: 40                      # range: 0 to 74.5 dB
  rx_gain_mode: "manual"              # "manual" or Automatic Gain Control: "fast_attack", "slow_attack"

modulation:
  type: "BPSK"                        # Modulation type: "BPSK", "QPSK", More to come
  symbol_rate: 250e3                  # Symbols per second
  samples_per_symbol: 8               # Samples per symbol
  roll_off: 0.35                      # Roll-off factor (alpha) for pulse shaping filter

framing:
  barker_code_enable: true            # Enable/disable Barker code preamble
  barker_code_length: 7               # Length of Barker code (choice: 7, 11 or 13)
  preamble_length: 16                 # Length of preamble in bits
  frame_size: 32                      # Payload size in bits

logging:
  log_level: "INFO"                   # Logging level: "DEBUG", "INFO", "WARNING", "ERROR"
  log_to_file: false                  # Enable/disable logging to file
  log_file_path: "radio_log.txt"      # Path to log file
  log_dir_path: "logs/"               # Directory to save log files
