radio:
  ip_address: "ip:192.168.0.151"      # ip address of sdr radio
  log_level: "DEBUG"                  # Log Level: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  queue_size: 32                      # Maxsize of RX and TX queues. Also determines the max number of messages stored for display in the TUI.
  debug_mode: True                    # If True, the system will run in debug mode with live plotting of signals.

transmitter:
  tx_cyclic_buffer: True             # Enable/disable cyclic buffer
  tx_gain_dB: 0                     # range: -90 to 0 dB
  tx_bandwidth: 1e6                   # TX bandwidth [Hz]
  tx_carrier: 866.5e6                 # TX local oscillator (carrier frequenzy)
  tx_buffer_size: 1024                # 2**10 samples 

receiver: 
  rx_gain_dB: 0                     # range: 0 to 73 dB
  rx_bandwidth: 1e6                 # RX bandwidth [Hz]
  rx_carrier: 866.5e6                 # RX local oscillator (carrier frequenzy)
  gain_mode: 'manual'                 # "manual" or Automatic Gain Control: "fast_attack", "slow_attack"
  buffer_size: 262144                  # 2**18 samples      

modulation:
  type: "qpsk"                        # Modulation type: "BPSK", "QPSK", More to come
  symbol_rate: 125e3                  # Symbols per second. symbol period = 1 / symbol_rate = 4 us
  samples_per_symbol: 8               # Samples per Symbol. Must be an integer. Determines the oversampling factor for pulse shaping and matched filtering.
  sample_rate: 1e6                    # EDIT ONLY THROUGH SYMBOL RATE AND SAMPLES PER SYMBOL (symbol_rate * samples_per_symbol)

coding:
  channel_coding_scheme: "hamming"     # Channel coding scheme: "hamming", More to come
  hamming_n: 15                        # Hamming code parameter n (total codeword length)
  hamming_k: 11                        # Hamming code parameter k (data length)
  scrambler_enable: true                # 
  scrambler_seed: 93                    # 
  scrambler_register_length: 7          # 

filter:
  rrc_roll_off: 0.5                   # Roll-off factor (alpha) for pulse shaping filter
  rrc_filter_span: 10                 # Filter span in symbols for RRC filter (total filter length = rrc_filter_span * samples_per_symbol)
  rrc_filter_scale_factor: 1          # (2**15-1) Scale factor for RRC filter coefficients to fit within int16 range for hardware filtering.
  hardware_filter_enable: False        # Enable/disable hardware RRC filtering on the SDR. If False, RRC filtering is done in software.
  hardware_filter_file: "rrc_filter_coefficients.ftr"  # File to store RRC filter coefficients for hardware filtering. Only used if rrc_filtering_enable is True.
  butterworth_enable: false           # 
  butterworth_order: 4                # Rolloff order 
  butterworth_cutoff_hz: 140e9        # Cutoff Freq. Adjust as needed 

barker_sequence:
  code_length: 13                     # Preamble length in bits. True Barker codes exist up to 13; 14-70 use deterministic Barker-like PN sequences.
  correlation_threshold: 0.033          # Correlation threshold for preamble detection. Scale factor to acknowledge signal peaks above the noise floor. Adjust based on observed noise levels and signal strength.

gold_sequence:
  code_length: 31
  code_index: 7
  correlation_threshold: 0.7


synchronization:
  nfft: 2048                   # FFT size for coarse frequency synchronization. 4096 provides a frequency resolution of sample_rate/nfft, which is approximately 500 Hz for a sample rate of 2 MHz. Adjust based on expected frequency offsets and desired resolution.
  signal_bw: 1e6                  # Loop bandwidth for Costas loop in Hz. Determines how quickly the loop can track frequency and phase variations. A common choice is around 1-5% of the symbol rate, so for a symbol rate of 125 kHz, a bandwidth of 2500 Hz (2% of symbol rate) is a reasonable starting point. Adjust based on expected frequency offsets and noise conditions.
  signal_power_threshold_dB: 1.0     # Threshold level above the measured noise floor in dB for considering a signal presence.
  costas_zeta: 0.707                     # Damping factor for Costas loop. A value of 0.707 (1/sqrt(2)) provides critical damping, which is a common choice for stable and responsive loop behavior. Adjust based on desired trade-off between stability and responsiveness.
  costas_K0: 1.0                         # VCO gain for costas loop.    
  costas_alpha: 0.02                    # Proportional gain for Costas loop (alternative to loop bandwidth). Adjust based on desired loop response. Ignored if costas_loop_bw is set.

plotter:
  num_rows: 200                    # Number of rows in waterfall display
  center_freq: 866.5e6             # Center frequency for display (Hz)
  time_plot_samples: 500           # Number of samples to show in time plot
  update_interval: 100             # Milliseconds between plot updates
  psd_nperseg: 1024                # FFT size for PSD calculation
  max_constellation_points: 500   # Max points in constellation diagram
  psd_window: 'hann'               # Window function for PSD
  psd_scaling: 'density'           # PSD scaling type
  psd_max_points: 2048             # Max points in PSD plot
  multi_window: True                  # If True, use multiple windows for different plots. If False, use a single window with subplots.
